// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_signin from "./routes/auth/signin.tsx";
import * as $auth_signout from "./routes/auth/signout.tsx";
import * as $auth_signup from "./routes/auth/signup.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/signin.tsx": $auth_signin,
    "./routes/auth/signout.tsx": $auth_signout,
    "./routes/auth/signup.tsx": $auth_signup,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
